from task import add, sub, mul, div, percentage, exponent
x=(int(input("Enter a number:")))
y=(int(input("Enter a number:")))
print(add(x, y))
x=(int(input("Enter a number:")))
y=(int(input("Enter a number:")))
print(sub(x, y))
x=(int(input("Enter a number:")))
y=(int(input("Enter a number:")))
print(mul(x, y))
x=(int(input("Enter a number:")))
y=(int(input("Enter a number:")))
print(div(x, y))
x=(int(input("Enter a number:")))
y=(int(input("Enter a number:")))
print(percentage(x, y))
x=(int(input("Enter a number:")))
y=(int(input("Enter a number:")))
print(exponent(x, y))
